### PR TITLE
Add api_key lookup

### LINKED ISSUE #10: Use the api key in the workspace
In ci.centos.org, we provision each workspace with a file called ~/.duffy.key that includes the appropriate API token, cicoclient should grab credentials from here (and perhaps fall back to using the environment if needed). 

This would make it harder to accidentally leak api keys in Jenkins shell jobs (which are set -xe by default)

### PR DESCRIPTION
**Pull request by detiber**
- Add api_key lookup to wrapper.py
  - Use api_key if provided
  - Use value of CICO_API_KEY
  - Use contents of ~/.duffy.key
  - Use contents of ~/duffy.key

- Update ansible module to simply default to None and use lookup from
wrapper

- Update shell.py to default to None and use lookup from wrapper.

Resolves #10

### CODE REVIEW

**Comment by detiber** [comment]
I'm still testing these changes, but wanted to try and allow for feedback on the approach taken before wrapping up.

**Comment by detiber** [comment]
I think this is good to go now, I've tested CicoWrapper, and the cico command line client, and the Ansible module.

**Comment by detiber** [comment]
@dmsimard @bstinsonmhk

**Comment by bstinsonmhk** [comment]
Tested this against our dev instance. Looks good to me.

**Comment by dmsimard** [comment]
hey @detiber I know that @bstinsonmhk already merged this but could you add some docs ? like here for example: https://github.com/CentOS/python-cicoclient/blob/master/docs/cli_usage.rst

**Comment by detiber** [comment]
@dmsimard most definitely, I'll work something up within the next few days.

**Pull request merged**
